language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --no-interaction --prefer-source

before_script:
  - wget https://github.com/infection/infection/releases/download/0.8.0/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.8.0/infection.phar.pubkey
  - chmod +x infection.phar

# Run here all same as in `composer ci`
script:
  - composer validate --no-check-all --strict
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpcpd src tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyse src tests
  - ./infection.phar --min-msi=48 --threads=4
  - composer outdated --direct

# public repo on Travis CI (without token)
after_success:
  - bash <(curl -s https://codecov.io/bash)
