language: php

php:
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/phan-ast/build

install:
  - composer install --no-interaction --prefer-source

before_script:
  - wget https://github.com/infection/infection/releases/download/0.8.0/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.8.0/infection.phar.pubkey
  - chmod +x infection.phar

# Run here all same as in `composer ci`
script:
  - composer validate --no-check-all --strict
  # Install phan separately because the tolerant-php-parser version may be behind.
  - composer create-project phan/phan=1.2.6 ~/phan-install; ~/phan-install/phan
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpcpd src tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - ./infection.phar --min-msi=48 --threads=4

# public repo on Travis CI (without token)
after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
